version: '3.1'

services:
  database:
    image: postgres:14.3
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ${DOCKER_FOLDER}/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s  

  app:
    build:
      context: .
      dockerfile: ${DOCKER_FOLDER}/application/Dockerfile
      args:
        - APP_CLI_NAME=${APP_CLI_NAME}
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env

networks:
  ghinfo:
    driver: bridge

volumes:
  pgdata:
    driver: local