version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: ${DOCKER_FOLDER}/application/Dockerfile
      args:
        - APP_CLI_NAME=${APP_CLI_NAME}
    depends_on:
    - database
    env_file:
      - .env 

  database:
    image: postgres:14.3
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ${DOCKER_FOLDER}/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ${DOCKER_FOLDER}/database/tables.sql:/docker-entrypoint-initdb.d/tables.sql # Will be created from migrations
      
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432

networks:
  ghinfo:
    driver: bridge

volumes:
  pgdata:
    driver: local