version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: ${DOCKER_FOLDER}/application/Dockerfile
    depends_on:
    - database
    env_file:
      - .env

  database:
    image: postgres:15.3
    volumes:
      - ${DOCKER_FOLDER}/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env

networks:
  ghinfo:
    driver: bridge

volumes:
  pgdata:
    driver: local